<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.calculator.gb.com/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ws.calculator.gb.com/">
	<wsdl:types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			attributeFormDefault="unqualified" elementFormDefault="qualified">
			<xs:import namespace="http://ws.calculator.gb.com/"
				schemaLocation="Types.xsd"></xs:import>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="getCalculationRequest">
		<wsdl:part element="tns:CalculationRequest" name="calculation" />
	</wsdl:message>
	<wsdl:message name="getCalculationResponse">
		<wsdl:part element="tns:CalculationResponse" name="body" />
	</wsdl:message>
	<wsdl:message name="calculatorFault">
		<wsdl:part name="body" element="tns:CalculatorFault" />
	</wsdl:message>
	<wsdl:portType name="CalculatorServicePortType">
		<wsdl:operation name="getCalculation">
			<wsdl:input message="tns:getCalculationRequest" />
			<wsdl:output message="tns:getCalculationResponse" />
			<wsdl:fault name="CalculatorFault" message="tns:calculatorFault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CalculatorSOAP" type="tns:CalculatorServicePortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="getCalculation">
			<soap:operation soapAction="getCalculation" style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="CalculatorFault">
				<soap:fault name="CalculatorFault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="calculatorService">
		<wsdl:port binding="tns:CalculatorSOAP" name="CalculatorServicePort">
			<soap:address location="http://localhost:8080/GBCalculator/calculator-ws" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
